# Makefile frontend for pure-Python project
# Generated by buildgen for: timu
#
# This Makefile wraps common build commands for convenience.
# The actual build is handled by uv_build via pyproject.toml

.PHONY: all sync build rebuild test lint lint-check format format-check \
        typecheck qa clean distclean wheel sdist dist check publish-test \
        publish upgrade coverage coverage-html docs diagrams release help

# Default target
all: build

# Sync environment (initial setup, installs dependencies + package)
sync:
	@uv sync

# Sync the editable install (pure Python: edits take effect immediately)
build:
	@uv sync

# Alias for build
rebuild: build

# Run tests
test:
	@uv run pytest tests/ -v

# Lint with ruff (applies fixes)
lint:
	@uv run ruff check --fix src/ tests/

# Lint with ruff (check only, no fixes)
lint-check:
	@uv run ruff check src/ tests/

# Format with ruff
format:
	@uv run ruff format src/ tests/

# Check formatting without modifying files
format-check:
	@uv run ruff format --check src/ tests/

# Type check with mypy (package and tests)
typecheck:
	@uv run mypy src/timu tests

# Run a full quality assurance check (non-mutating; mirrors CI)
qa: lint-check format-check typecheck test

# Build wheel
wheel:
	@uv build --wheel

# Build source distribution
sdist:
	@uv build --sdist

# Check distributions with twine
check:
	@uv run twine check dist/*

# Build both wheel and sdist
dist: wheel sdist check

# Publish to TestPyPI
publish-test: check
	@uv run twine upload --repository testpypi dist/*

# Publish to PyPI
publish: check
	@uv run twine upload dist/*

# Upgrade all dependencies
upgrade:
	@uv lock --upgrade
	@uv sync

# Run tests with coverage
coverage:
	@uv run pytest tests/ -v --cov=src/timu --cov-report=term-missing

# Generate HTML coverage report
coverage-html:
	@uv run pytest tests/ -v --cov=src/timu --cov-report=html
	@echo "Coverage report: htmlcov/index.html"

# Build documentation (sphinx is fetched on demand; add it to the dev group
# to pin a version)
docs:
	@uv run --with sphinx sphinx-build -b html docs/ docs/_build/html

# Regenerate docs/media/*.svg from their .d2 sources (d2 with the TALA layout engine)
diagrams:
	@for f in docs/media/*.d2; do d2 --layout=tala "$$f" "$${f%.d2}.svg" || exit 1; done

# Create a release (bump version, tag, push)
release:
	@echo "Current version: $$(grep '^version' pyproject.toml | head -1)"
	@read -p "New version: " version; \
	sed "s/^version = .*/version = \"$$version\"/" pyproject.toml > pyproject.toml.tmp && mv pyproject.toml.tmp pyproject.toml; \
	git add pyproject.toml; \
	git commit -m "Bump version to $$version"; \
	git tag -a "v$$version" -m "Release $$version"; \
	echo "Tagged v$$version. Run 'git push && git push --tags' to publish."

# Clean build artifacts
clean:
	@rm -rf build/
	@rm -rf dist/
	@rm -rf *.egg-info/
	@rm -rf src/*.egg-info/
	@rm -rf .pytest_cache/
	@find . -name "*.so" -delete
	@find . -name "*.pyd" -delete
	@find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

# Clean everything, including the resolved environment
distclean: clean
	@rm -rf .venv/ .mypy_cache/ .ruff_cache/

# Show help
help:
	@echo "Available targets:"
	@echo "  all          - Sync the environment (default)"
	@echo "  sync         - Sync environment (initial setup)"
	@echo "  build        - Sync the editable install"
	@echo "  rebuild      - Alias for build"
	@echo "  test         - Run tests"
	@echo "  lint         - Lint with ruff (applies fixes)"
	@echo "  lint-check   - Lint with ruff (check only)"
	@echo "  format       - Format with ruff"
	@echo "  format-check - Check formatting without modifying files"
	@echo "  typecheck    - Type check the package and tests with mypy"
	@echo "  qa           - Run full quality assurance (non-mutating: lint-check, format-check, typecheck, test)"
	@echo "  wheel        - Build wheel distribution"
	@echo "  sdist        - Build source distribution"
	@echo "  dist         - Build both wheel and sdist"
	@echo "  check        - Check distributions with twine"
	@echo "  publish-test - Publish to TestPyPI"
	@echo "  publish      - Publish to PyPI"
	@echo "  upgrade      - Upgrade all dependencies"
	@echo "  coverage     - Run tests with coverage"
	@echo "  coverage-html - Generate HTML coverage report"
	@echo "  docs         - Build documentation with Sphinx"
	@echo "  diagrams     - Regenerate docs/media/*.svg from .d2 sources (d2, TALA)"
	@echo "  release      - Bump version, tag, and prepare release"
	@echo "  clean        - Remove build artifacts"
	@echo "  distclean    - Remove all generated files"
	@echo "  help         - Show this help message"
